#Import the required library.
import numpy as np
import pandas as pd
import requests
from io import StringIO
#Use this section to suppress warnings generated by code.
def warn(*args,**kwargs):
    pass
import warnings
warnings.warn=warn
warnings.filterwarnings('ignore')
#Extract the required GDP data from the URL.
URL='https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
headers={"User-Agent":"Mozilla/5.0(Windows NT 10.0;Win64; x64)"}
response=requests.get(URL,headers=headers)
response.raise_for_status()
html=response.text
#Extract the tables from the webpage using pandas.Retain table no.3 as the required dataframe.
tables=pd.read_html(StringIO(html))
df=tables[2]
#Replace all the column headers with column numbers.
df.columns=range(df.shape[1])
#Retain columns with index 0 and 2(Name of the countries and value of GDP quoated by IMF)
df=df[[0,2]]
#Retain columns with index 1 to 10, indicating the top 10 largest economies of the world.
df=df.iloc[1:11,:]
#Assign column names as "Country" and "GDP(Million USD)"
df.columns=['Country','GDP(Million USD)']
#Change the datatype of the 'GDP(Million USD)' column to integer by using astype()method.
df['GDP(Million USd)']=(df['GDP(Million USD)'].astype(str)
                        .str.replace(',','',regex=False)
                        .str.replace('-','',regex=False))
df['GDP(Million USD)']=pd.to_numeric(df['GDP(Million USD)'],errors='coerce')
#Convert the GDP value in Million USD to Billion USD.
df[['GDP(Billion USD)']]=df[['GDP(Million USD)']]/1000
#Use numpy.round()method to round the value to 2Decimal places.
df[['GDP(Million USD)']]=np.round(df[['GDP(Million USD)']],2)
#Rename the column header from 'GDP(Million USD)' to 'GDP(Billion USD)'
df.rename(columns={"GDP(MillionUSD)":"GDP(Billion USD)"})
print(df)
#Load the DataFrame to the CSV file named"Largest_economies.csv"
df.to_csv('./Largest_economies.csv')